Ensure EDSP doesn't use a dangling architecture string
../apt-pkg/edsp.cc:861:23: error: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
   const char *arch = _config->Find("APT::Architecture").c_str();

Compilers are probably optimizing it the way the patch does by hand now. Small
string optimisation helps likely as well. Othwise that should have failed left
and right as EDSP is used by experimental and such builders to talk to aspcud.

Reported-By: clang


Debian: 90a7a5e32643a67f4245460e7659d9dee230e9e7