error: Extract operator<< into error.cc (de-inline it)
Extract the code, and reformat it with clang-format so we can
modify it.


Debian: b0e2c9de13ff1df2f0f1cba2ceed88c710efea3a