Avoid using unqualified make_pair potentially triggering ftbfs
If the includes are slightly changed, we end with an error here:
apt/apt-pkg/depcache.cc:2059:31: error: ‘make_pair’ was not declared in this scope; did you mean ‘std::make_pair’?

Yes, we mean std::make_pair, but we can avoid the explicit call
altogether by using emplace_back instead of push_back.


Debian: a0e16ddd7b274bf6b1383873315020f215e6f67a