rpmpm.cc (pkgRPMLibPM::Process): commented out unused code which breaks gcc-4.1
rpm/rpmpm.cc:932: error: jump to label ‘exit’
rpm/rpmpm.cc:791: error:   from here
rpm/rpmpm.cc:846: error:   crosses initialization of ‘int repackage’
rpm/rpmpm.cc:843: error:   crosses initialization of ‘int packagesTotal’

(Originally c3e85a18541b2d98fc219f901c7eabcb77caa496 at http://apt-rpm.org/scm/apt.git )

(Originally 64c8ec835a4a87f7586464272fb13d6013105526 at https://gitlab.com/apt-rpm/apt-rpm.git )